### ISSUE TITLE
在Google浏览器上搜索应用图标后列表是空白的

### ISSUE THREAD

**Issue by OwnStupid** [YuKongA/HQ-ICON#14]
在Google浏览器上搜索应用图标后列表是空白的，搜索任何应用都无法搜索到，URL的请求参数没有发生任何变化。
![image](https://github.com/user-attachments/assets/160b66df-67c6-4098-9b3a-dea0c44b6b97)

**Comment by YuKongA** [comment]
> 在Google浏览器上搜索应用图标后列表是空白的，搜索任何应用都无法搜索到，URL的请求参数没有发生任何变化。 ![image](https://private-user-images.githubusercontent.com/79457006/393560750-160b66df-67c6-4098-9b3a-dea0c44b6b97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2Mjg4MTAsIm5iZiI6MTczMzYyODUxMCwicGF0aCI6Ii83OTQ1NzAwNi8zOTM1NjA3NTAtMTYwYjY2ZGYtNjdjNi00MDk4LTliM2EtZGVhMGM0NGI2Yjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDAzMjgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMDA3OTRlZWE3YThjN2UwMzEzZGI1NTQwMmYzNjdiNTE5NGM2ZDE0MmZjMTRkMDI5MjU3OGMyMWUwYWQ3NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CZMXEt6-uIp6E6sElZJcYi3QGMsmj5UF2iQtiPL9lpg)

再试试，应该好了
